### ISSUE TITLE
Configuration: areas and filesystems

### ISSUE THREAD

**Issue by ato** [nla/doss#33]
We need a way to configure the areas and filesystems DOSS uses. Each area is made up of one or more filesystems. Each filesystem stores a copy of every blob in the area. In normal production usage there will be 2 areas: *area.staging* and *area.master*; and 3 filesystems: *fs.staging*, *fs.display* and *fs.preservation*.

See #29 for more background about the staging area. For the master area DOSS needs to make at least two copies of each blob, one on a disk array for online access and one on a tape-backed preservation filesystem (currently running SAM-QFS). The preservation filesystem actually itself makes multiple tape copies, some of the tapes get sent to an offsite location for disaster recovery, others sit in a tape robot onsite and can be used to restore the display copy in the event something happens to it. We had to make use of this recovery mechanism in 2011 after an operating system bug corrupted the display filesystem, it's not just paranoia.

```ini
[defaults.put]
target = area.staging

[area.staging]
fs = staging

[area.master]
fs = display, preservation
container = tar

[fs.staging]
path = /staging

[fs.display]
# online spinning disk backed filesystem
path = /display

[fs.preservation]
# nearline tape backed filesystem
path = /sam/master
```

I really want to use something like Python's [configparser](http://docs.python.org/3/library/configparser.html) format for this. [ini4j](http://ini4j.sourceforge.net/)'s [ConfigParser](http://ini4j.sourceforge.net/apidocs/index.html?org/ini4j/ConfigParser.html) class appears to be a reasonable Java implementation of it.

[Commons Configuration](https://commons.apache.org/proper/commons-configuration/) seems to be the other popular choice, it does a lot more but looks a bit too overengineered for our needs.

**Comment by brycollins** [comment]
Implemented using ini4j
