### ISSUE TITLE
Blob digests (checksums)

### ISSUE THREAD

**Issue by ato** [nla/doss#42]
Blobs should have digests associated with them. Keep in mind that we may want to change digest algorithm in the future. `doss stat` should show the digests for the blob.

**Comment by brycollins** [comment]
Digests are stored in H2 for both Containers and Blobs.
There is a configuration option for a list of preferred digest algorithms, the last in the list being the current algorithm.
If a client makes a blob.digest(algorithm) call, it will store the result in H2.
The Archiver will also store digests in H2 during the verify phase.
This issue should remain open until all functions relating to Digests are implemented.
(i.e Scrubber)
