### ISSUE TITLE
Native access: NFS server

### ISSUE THREAD

**Issue by ato** [nla/doss#56]
It's looking like NFS might be the best option for implementing the native interface in Java as FUSE's performance apparently can be pretty bad and libfuse via JNA looks a bit painful. [jpnfs] seems like it might be a decent Java implementation. It might be as simple as implementing the [VirtualFileSystem] interface. We should try out a dummy implementation and check if it works as advertised.

[jpnfs]: https://github.com/dCache/jpnfs/
[VirtualFileSystem]: https://github.com/dCache/jpnfs/blob/master/src/org/dcache/nfs/vfs/VirtualFileSystem.java#L26

**Comment by brycollins** [comment]
NFS implementation works, few funnies such as odd delay in startup on RHEL machines, otherwise works well for IIPSrv and also for Wowza.
